// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBRsHS8dL3MhmjNWdAUlAqEo_DqsXf34i8',
    appId: '1:956728090370:web:c16f75f1e123a13068ec1b',
    messagingSenderId: '956728090370',
    projectId: 'ecommerce-a82c6',
    authDomain: 'ecommerce-a82c6.firebaseapp.com',
    storageBucket: 'ecommerce-a82c6.appspot.com',
    measurementId: 'G-896ZLSE8B4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAsi-JPxReomFZPIzM53kenyPRja9VhZzs',
    appId: '1:956728090370:android:9719ea2766075a5468ec1b',
    messagingSenderId: '956728090370',
    projectId: 'ecommerce-a82c6',
    storageBucket: 'ecommerce-a82c6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCLTw4u-m2wNme4V5M7gKzrAJ7_qgMc5wU',
    appId: '1:956728090370:ios:cf8e73fa9585824668ec1b',
    messagingSenderId: '956728090370',
    projectId: 'ecommerce-a82c6',
    storageBucket: 'ecommerce-a82c6.appspot.com',
    iosClientId: '956728090370-s2hs4n1tju6acmfakb3r1npvobujm8r1.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCLTw4u-m2wNme4V5M7gKzrAJ7_qgMc5wU',
    appId: '1:956728090370:ios:cf8e73fa9585824668ec1b',
    messagingSenderId: '956728090370',
    projectId: 'ecommerce-a82c6',
    storageBucket: 'ecommerce-a82c6.appspot.com',
    iosClientId: '956728090370-s2hs4n1tju6acmfakb3r1npvobujm8r1.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecommerce',
  );
}
